name: Tests
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - name: install
        run: make install install_abci
      # Cache bin
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary

  test_abci_apps:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - name: test_abci_apps
        run: abci/tests/test_app/test.sh
        shell: bash

  test_abci_cli:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - name: test_abci_cli
        run: abci/tests/test_cli/test.sh
        shell: bash

  test_apps:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - name: test_apps
        run: test/app/test.sh
        shell: bash

  test_persistence:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - name: test_persistence
        run: test/persist/test_failure_indcies.sh
        shell: bash
